### ISSUE TITLE
type c can connetcor pinout 

### ISSUE THREAD

**Issue by anscipione** [bigtreetech/HermitCrab#10]
i can't find the pinout of type c connector of the tool board.

**Comment by p-v-n** [comment]
I believe it's something similar to this: https://media.digikey.com/pdf/Data%20Sheets/Amphenol%20PDFs/C12402012-4.pdf

**Comment by mikerocklewitz** [comment]
Schematics for everything have been uploaded the other day. Check github

**Comment by Voodoobrew101** [comment]
It uses usb-c a-type pinout. center 2 are high low. Outside are power power like normal except thay are 24v so they will burn up a standard usb device like the BTT EBB42 boards.
