### ISSUE TITLE
Missing board specs

### ISSUE THREAD

**Issue by mikerocklewitz** [bigtreetech/HermitCrab#13]
I cant find information on the current limit for the hermit crab can....how big of a heater can i stick on the thing? Nobody has a straight answer.

@bigtreetech

**Comment by cd85233** [comment]
Also how much current can the 5V source?

**Comment by mikerocklewitz** [comment]
Ive been told less than 6 amps for the entire board.  No clue what the limit is for 5v only.

Schematics were uploaded the other day.
