### ISSUE TITLE
how to fix bltouch ?

### ISSUE THREAD

**Issue by grimlokason** [bigtreetech/HermitCrab#3]
Hello

in HermitCrab/CanbusKlipper/Klipper/Canbus_hotend_pins.cfg  you are specifiying the bltouch offset but there is no information on which support to use neither in the config file nor in the pdf.

Is it possible to get it or a link to it ?

Best regards.

**Comment by thisiskeithb** [comment]
>  you are specifiying the bltouch offset but there is no information on which support to use neither in the config file nor in the pdf

Insert your own values. Those are just dummy values to get you started since everyone's printer/hotend is different.

**Comment by grimlokason** [comment]
ok, thank you !
